"""Git tool — initialize repos and push completed projects."""

import os
from dataclasses import dataclass

from app.tools.shell import ShellTool


@dataclass
class GitResult:
    success: bool
    message: str
    repo_url: str | None = None


class GitTool:
    """Git operations for the agent workspace."""

    def __init__(self, workspace: str = "./workspace"):
        self.workspace = os.path.abspath(workspace)
        self._shell = ShellTool(workspace=self.workspace, timeout=60)

    async def init_repo(self, project_path: str) -> GitResult:
        """Initialize a git repository in the project directory."""
        full_path = os.path.join(self.workspace, project_path)
        if not os.path.isdir(full_path):
            return GitResult(success=False, message=f"Directory not found: {project_path}")

        result = await self._shell.execute(
            f"cd {full_path} && git init && git add -A && git commit -m 'Initial commit — generated by TriMind Agent'"
        )
        if result.success:
            return GitResult(success=True, message="Git repository initialized with initial commit.")
        return GitResult(success=False, message=f"Git init failed: {result.output}")

    async def create_and_push(
        self,
        project_path: str,
        repo_name: str,
        remote_url: str | None = None,
        platform: str = "github",
        token: str | None = None,
        username: str | None = None,
    ) -> GitResult:
        """Create a remote repository and push the project.

        If remote_url is provided, push to that URL directly.
        Otherwise, try to create a repo via the platform API.
        """
        full_path = os.path.join(self.workspace, project_path)
        if not os.path.isdir(full_path):
            return GitResult(success=False, message=f"Directory not found: {project_path}")

        # Ensure git is initialized
        git_dir = os.path.join(full_path, ".git")
        if not os.path.isdir(git_dir):
            init_result = await self.init_repo(project_path)
            if not init_result.success:
                return init_result

        # If a remote URL is given, just add remote and push
        if remote_url:
            return await self._push_to_remote(full_path, remote_url)

        # Try to create a repo via API
        if platform == "github" and token:
            return await self._create_github_repo(full_path, repo_name, token, username)

        return GitResult(
            success=False,
            message="No remote URL or API token provided. Please provide a remote URL or configure a GitHub token in settings.",
        )

    async def _push_to_remote(self, full_path: str, remote_url: str) -> GitResult:
        """Push to a given remote URL."""
        cmds = [
            f"cd {full_path} && git remote remove origin 2>/dev/null; true",
            f"cd {full_path} && git remote add origin {remote_url}",
            f"cd {full_path} && git branch -M main",
            f"cd {full_path} && git push -u origin main",
        ]
        for cmd in cmds:
            result = await self._shell.execute(cmd)

        # Check last push
        result = await self._shell.execute(f"cd {full_path} && git push -u origin main 2>&1")
        if result.success or "Everything up-to-date" in result.output:
            return GitResult(success=True, message="Pushed to remote successfully.", repo_url=remote_url)
        return GitResult(success=False, message=f"Push failed: {result.output}")

    async def _create_github_repo(
        self, full_path: str, repo_name: str, token: str, username: str | None
    ) -> GitResult:
        """Create a GitHub repo via API and push."""
        # Create the repo
        create_cmd = (
            f'curl -s -X POST https://api.github.com/user/repos '
            f'-H "Authorization: token {token}" '
            f'-H "Content-Type: application/json" '
            f'-d \'{{"name": "{repo_name}", "private": false, "auto_init": false}}\''
        )
        result = await self._shell.execute(create_cmd)

        if not result.success:
            return GitResult(success=False, message=f"GitHub API error: {result.output}")

        # Parse response to get clone URL
        import json
        try:
            data = json.loads(result.stdout)
            clone_url = data.get("clone_url", "")
            html_url = data.get("html_url", "")
            if not clone_url:
                error_msg = data.get("message", "Unknown error")
                return GitResult(success=False, message=f"GitHub API error: {error_msg}")
        except json.JSONDecodeError:
            return GitResult(success=False, message=f"Failed to parse GitHub response: {result.stdout[:200]}")

        # Use token in URL for auth
        auth_url = clone_url.replace("https://", f"https://{token}@")

        push_result = await self._push_to_remote(full_path, auth_url)
        if push_result.success:
            push_result.repo_url = html_url
            push_result.message = f"Repository created and pushed: {html_url}"
        return push_result

    async def add_commit_push(
        self, project_path: str, message: str = "Update from TriMind Agent"
    ) -> GitResult:
        """Add all changes, commit, and push."""
        full_path = os.path.join(self.workspace, project_path)
        result = await self._shell.execute(
            f"cd {full_path} && git add -A && git commit -m '{message}' && git push 2>&1"
        )
        if result.success or "nothing to commit" in result.output:
            return GitResult(success=True, message="Changes committed and pushed.")
        return GitResult(success=False, message=f"Git error: {result.output}")

    async def get_status(self, project_path: str) -> GitResult:
        """Get git status of a project."""
        full_path = os.path.join(self.workspace, project_path)
        result = await self._shell.execute(f"cd {full_path} && git status --short 2>&1")
        return GitResult(success=result.success, message=result.output)
